# Generated by Django 3.1.7 on 2021-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
